baseURL: letoniabrasil.org
relativeurls: false

languageCode: en-us
title: "Letonia Brasil"
publishDir: docs

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

googleAnalytics: UA-2167798-10


enableEmoji: true

params:
  description: Site da Associação Brasileira de Cultura Leta.
  background: "images/background.jpg"
  enableBlogPost: true
  enableTOC: false
  #customMenus:
  #- name: Notes
  #  url: https://hossainnotes.netlify.app/docs/example/
  newsletter:
    enable: false

  author:
    name: "Letonia Brasil"
    nickname: "Letonia Brasil"
    image: "images/logo.png"
    greeting: ""
