baseURL: https://letoniabrasil.org/

languageCode: pt-br
title: "Letonia Brasil"
publishDir: docs

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

googleAnalytics: UA-2167798-10
enableEmoji: true

params:
  description: Site da Associação Brasileira de Cultura Leta.
  background: "images/background.jpg"
  enableBlogPost: true
  enableTOC: false
  newsletter:
    enable: false

  author:
    name: "Letonia Brasil"
    nickname: "Letonia Brasil"
    image: "images/logo.png"
    greeting: ""
